# Numpy

In [2]:
import numpy as np

## Basic

#### Q1 : A vector of 20 integers from 1 to 20

In [7]:
output = np.arange(1, 21, dtype=int)
output

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### 2 : A matrix of 4 rows and 5 columns with radnom integers between 10 and 50

In [14]:
output = np.random.randint(10, 51, 20).reshape(4,5)
output

array([[33, 30, 36, 12, 27],
       [32, 39, 28, 30, 17],
       [32, 38, 30, 18, 27],
       [22, 20, 37, 29, 33]])

In [19]:
result = np.random.randint(10, 51, (4,5))
result

array([[28, 45, 48, 10, 44],
       [39, 32, 48, 33, 10],
       [25, 11, 46, 47, 36],
       [40, 21, 20, 39, 32]])

#### Q3 : A identity matrix of 3 rows and 3 columns

In [17]:
output = np.eye(3,3)
output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
result = np.identity(3)
result

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q4 : A vector of 10 evenly spaced numbers between 0 and 1

In [22]:
output = np.linspace(0.0, 1.0, num=10, endpoint=False)
output

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### Q5 : A matrix of 3x3 filled with 7 for main diagonal

In [25]:
output = np.eye(4)*7
output


array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

#### Q6: Creates a matrix, calculates column means, and normalizes it.

In [37]:
matrix = np.random.randint(-100, 101, (3, 4))
print(matrix,'\n')

col_means = matrix.mean(axis=0)
print(col_means,'\n')

output = matrix - col_means
print(output,'\n')

# check the new column means, should be 0
new_col_means = output.mean(axis=0)
print(new_col_means,'\n')

rounded_new_means = np.round(new_col_means, decimals=10)
print(rounded_new_means)

[[ -8 -13  52   7]
 [-94  51  21 -82]
 [ 63  19  32 -13]] 

[-13.          19.          35.         -29.33333333] 

[[  5.         -32.          17.          36.33333333]
 [-81.          32.         -14.         -52.66666667]
 [ 76.           0.          -3.          16.33333333]] 

[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.55271368e-15] 

[ 0.  0.  0. -0.]


#### Q7: Creates a matrix, calculates column std, and normalizes it.

In [39]:
matrix = np.random.randint(-100, 101, (3, 4))
print(matrix,'\n')

col_std = matrix.std(axis=0)
print(col_std,'\n')

output = matrix / col_std
print(output,'\n')

# check the new column std, should be 1
new_col_std = output.std(axis=0)
print(new_col_std)

[[ 46 -28 -31 -72]
 [ 73 -27   3 -29]
 [ 67  76  14  82]] 

[11.5758369  48.79207586 19.15434386 64.88108781] 

[[ 3.97379476 -0.57386368 -1.61843184 -1.10972245]
 [ 6.30623951 -0.55336854  0.15662244 -0.44697154]
 [ 5.78791845  1.55762998  0.7309047   1.26385057]] 

[1. 1. 1. 1.] 



#### Q8: Scale the values of the matrix to the range [0, 1]

In [40]:
matrix = np.random.randint(-100, 101, (3, 4))
print(matrix, 'n')

scaled_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(scaled_matrix)

Original Matrix:
[[ -1  56 -50  -2]
 [-81 -83   3  16]
 [-52  99 -22  17]]

Scaled Matrix between 0 and 1:
[[0.45054945 0.76373626 0.18131868 0.44505495]
 [0.01098901 0.         0.47252747 0.54395604]
 [0.17032967 1.         0.33516484 0.54945055]]


#### Q9: Sum two vectors

In [46]:
vector1 = np.random.randint(0, 10, 5)
vector2 = np.random.randint(0, 10, 5)

print (vector1, vector2)

result = (vector1 + vector2)
print(result)

[7 1 2 6 9] [3 8 1 6 8]
[10  9  3 12 17]


#### Q10: Multply a matrix in a constant number

In [51]:
matrix = np.random.randint(0, 10, (5,4))

print (matrix, '\n')

result = (matrix *5)
print(result)

[[3 1 2 6]
 [4 5 9 9]
 [4 1 7 8]
 [7 9 3 0]
 [3 6 0 0]] 

[[15  5 10 30]
 [20 25 45 45]
 [20  5 35 40]
 [35 45 15  0]
 [15 30  0  0]]


#### Q11: Create vector C with the maximum of corresponding elements from A and B

In [54]:
A = np.array([1, 3, 5, 7, 9])
B = np.array([2, 4, 6, 8, 10])
print(A, B, '\n')

C = np.maximum(A, B)
print(C)

[1 3 5 7 9] [ 2  4  6  8 10] 

[ 2  4  6  8 10]


#### Q12

#### Q13: Mines a vector from matrix rows

In [59]:
matrix = np.random.randint(-20, 21, (5, 4))
print(matrix,'\n')

vector = np.random.randint(0, 10, (1,4))
print(vector,'\n')

output = matrix - vector
print(output)

[[-14  20   8 -10]
 [  6   7   7 -15]
 [ -9 -16  -3   7]
 [-10  12   9  20]
 [  2  10  20  15]] 

[[8 7 0 7]] 

[[-22  13   8 -17]
 [ -2   0   7 -22]
 [-17 -23  -3   0]
 [-18   5   9  13]
 [ -6   3  20   8]] 



#### Q14: Create a 3x4 matrix from a vector of numbers 0 to 11

In [62]:
vector = np.arange(12)

matrix = vector.reshape(3, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Q15: Create a 3x4 matrix from a vector of numbers 0 to 11 (column first)

In [63]:
vector = np.arange(12)

matrix = vector.reshape(4, 3).T
print(matrix)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


#### Q16

In [67]:
matrix = np.random.randint(-20, 21, (5, 5))
print(matrix, '\n')

output = matrix[(0,2),:]
output

[[  1   1   8  18  -4]
 [  4   3  17   9   9]
 [  0   7  16  19  10]
 [ -9 -16 -18 -15  18]
 [-15 -12 -15   3  20]] 



array([[ 1,  1,  8, 18, -4],
       [ 0,  7, 16, 19, 10]])

#### Q17

In [68]:
matrix = np.random.randint(-20, 21, (5, 5))
print(matrix, '\n')

submatrix = matrix[0:2,3:5]
submatrix

[[-13  15   2  12  13]
 [  4 -11 -16   7 -18]
 [-17   3  -9   7  16]
 [ 10 -18   9  -2   7]
 [ -4   3  17 -18  15]] 



array([[ 12,  13],
       [  7, -18]])

#### Q18

In [75]:
matrix = np.random.randint(-20, 21, (5, 5))
print(matrix, '\n')

matrix[matrix >= 15] = -1
matrix

[[ -6 -18  20  18  13]
 [ -8  -1 -20 -20  -6]
 [-14  -8 -12 -20   0]
 [  5  10   4  -9   7]
 [ -6  16  -4  -8  10]] 



array([[ -6, -18,  -1,  -1,  13],
       [ -8,  -1, -20, -20,  -6],
       [-14,  -8, -12, -20,   0],
       [  5,  10,   4,  -9,   7],
       [ -6,  -1,  -4,  -8,  10]])

#### Q19: Create a 100x2 matrix representing 100 points in a 2D coordinate system. Calculate the Euclidean distance of each point from the origin (0, 0). Sort the points based on their distances from the origin

In [78]:
# Step 1: Generate a 100x2 matrix with random numbers
points = np.random.randint(0, 10, (10, 2))
print(points, '\n')

# Step 2: Calculate the Euclidean distance of each point from the origin
distances = np.sqrt(np.sum(points**2, axis=1))
print(distances, '\n')

# Step 3: Sort the points based on their distances from the origin
sorted_indices = np.argsort(distances)
print(sorted_indices, '\n')

sorted_points = points[sorted_indices]
print(sorted_points)

[[2 5]
 [8 6]
 [3 4]
 [6 5]
 [8 9]
 [2 5]
 [4 6]
 [7 5]
 [2 3]
 [9 5]] 

[ 5.38516481 10.          5.          7.81024968 12.04159458  5.38516481
  7.21110255  8.60232527  3.60555128 10.29563014] 

[8 2 0 5 6 3 7 1 9 4] 

[[2 3]
 [3 4]
 [2 5]
 [2 5]
 [4 6]
 [6 5]
 [7 5]
 [8 6]
 [9 5]
 [8 9]]


#### 20: Generate a vector of 100 random numbers between 0 and 1. Replace numbers greater than 0.58 with 1 and numbers less than or equal to 0.58 with 0.

In [ ]:
# Step 1: Generate a vector of 100 random numbers between 0 and 1
vector = np.random.rand(100)
print("Generated Vector:")
print(vector)

# Step 2: Replace numbers greater than 0.58 with 1 and numbers less than or equal to 0.58 with 0
vector[vector > 0.58] = 1
vector[vector <= 0.58] = 0

print("\nModified Vector:")
print(vector)

21. Create five separate 3-element vectors and concatenate them to form a 5x3 matrix.

In [ ]:
import numpy as np

# Create five separate 3-element vectors
vector1 = np.random.rand(3)
vector2 = np.random.rand(3)
vector3 = np.random.rand(3)
vector4 = np.random.rand(3)
vector5 = np.random.rand(3)

# Concatenate them to form a 5x3 matrix
matrix = np.vstack((vector1, vector2, vector3, vector4, vector5))
print(matrix)

22. Create five separate 3-element vectors and concatenate them to form a 3x5 matrix.

In [ ]:
import numpy as np

# Create five separate 3-element vectors
vector1 = np.random.rand(3)
vector2 = np.random.rand(3)
vector3 = np.random.rand(3)
vector4 = np.random.rand(3)
vector5 = np.random.rand(3)

# Concatenate them to form a 3x5 matrix
matrix = np.hstack((vector1, vector2, vector3, vector4, vector5)).reshape(3, 5)
print(matrix)

23. Create five separate 3-element vectors and concatenate them to form a 1x3x5 tensor.

In [ ]:
import numpy as np

# Create five separate 3-element vectors
vector1 = np.random.rand(3)
vector2 = np.random.rand(3)
vector3 = np.random.rand(3)
vector4 = np.random.rand(3)
vector5 = np.random.rand(3)

# Concatenate them to form a 1x3x5 tensor
tensor = np.array([vector1, vector2, vector3, vector4, vector5]).reshape(1, 3, 5)
print(tensor)

24. Create a 6x6 matrix and then return all the numbers in the first row and first column as a vector.

In [ ]:
import numpy as np

# Create a 6x6 matrix
matrix = np.random.rand(6, 6)

# Extract the first row and first column
first_row = matrix[0, :]
first_column = matrix[:, 0]

# Concatenate them into a single vector
result_vector = np.concatenate((first_row, first_column))
print(result_vector)

25. Create a 10x10 matrix where each element is the product of its row and column indices, and set the diagonal elements to zero.

In [ ]:
import numpy as np

# Create a 10x10 matrix where each element is the product of its row and column indices
matrix = np.fromfunction(lambda i, j: (i + 1) * (j + 1), (10, 10))

# Set the diagonal elements to zero
np.fill_diagonal(matrix, 0)
print(matrix)

26. Create a 2x3x4 tensor and then transpose it to a 4x3x2 tensor.

In [ ]:
import numpy as np

# Create a 2x3x4 tensor
tensor = np.random.rand(2, 3, 4)

# Transpose it to a 4x3x2 tensor
transposed_tensor = np.transpose(tensor, (2, 1, 0))
print(transposed_tensor)

## Intermidiate

#### 29

#### 29

#### 29

#### 29

#### 29

#### 29

#### 29